# Generated by Django 2.1.2 on 2018-12-10 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_myuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(blank=True, height_field=100, upload_to='', verbose_name='avatar', width_field=100),
        ),
    ]
